CREATE TABLE CLIENTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(100),
    PRECO DECIMAL(10,2) NOT NULL
);

CREATE TABLE PEDIDOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTES (ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL DECIMAL(10,2) NOT NULL
);

CREATE TABLE ITEM_PEDIDOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDOS (ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTOS (ID),
    QUANTIDADE INTEGER NOT NULL

);